# Playbook to update and upgrade apt packages on all hosts
- hosts: all
  become: yes
  #become_user: rogier
  tasks:

  - name: Get hostname of selected hosts
    hosts: your_host_group_or_selection
    tasks:
      - name: Display hostname
        debug:
          msg: "The hostname is {{ ansible_hostname }}"